#Unlocked next province
#Thu May 01 00:36:59 WIB 2025
# Unlocked next province
# Updated full list of Indonesian provinces
Java=false
Kalimantan=true
Sulawesi=true
Sumatra=true
Papua=true
Bali=true
NusaTenggaraBarat=true
NusaTenggaraTimur=true
Maluku=true
MalukuUtara=true
Aceh=true
Riau=true
KepulauanRiau=true
Jambi=true
SumateraBarat=true
SumateraUtara=true
SumateraSelatan=true
BangkaBelitung=true
Banten=true
JawaBarat=true
JawaTengah=true
JawaTimur=true
Yogyakarta=true
KalimantanBarat=true
KalimantanSelatan=true
KalimantanTengah=true
KalimantanTimur=true
KalimantanUtara=true
SulawesiBarat=true
SulawesiSelatan=true
SulawesiTengah=true
SulawesiTenggara=true
SulawesiUtara=true
Gorontalo=true
PapuaBarat=true
PapuaPegunungan=true
PapuaSelatan=true
PapuaTengah=true
PapuaBaratDaya=true
